version: '2'
services:
  app:
    build:
      context: .
    command: 'yarn test'
    depends_on:
      - redis
    env_file:
      - .env
    mem_reservation: "128m"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    working_dir: "/app"

  redis:
    image: redis
    expose:
      - '6379'
