services:
  test:
    build: .
    command: make ci
    depends_on:
      - redis
    volumes:
      - .:/service
      - /service/node_modules
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
    expose:
      - 6379
